services:
  - type: web
    name: cycle-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: CHANNEL_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
